mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from tinyapp.views import UserRegistrationView
from tinyapp.views import UrlListView
from tinyapp.views import UrlCreateView
from tinyapp.views import UrlRedirectView
from tinyapp.views import UrlDeleteView
from tinyapp.views import UrlUpdateView
from tinyapp.views import UserLoginView
from tinyapp.views import SeeAdminsView
from django.contrib.auth.views import LogoutView, PasswordChangeView

urlpatterns = [
    path('', UrlListView.as_view(), name='user-list'),
    path('admin/', admin.site.urls),  
    path('register/', UserRegistrationView.as_view(),name='register-user'),
    path('urls/', UrlListView.as_view(), name='url-list'),
    path('urls/new/', UrlCreateView.as_view(), name='url-new'),
    path('urls/<pk>/<slug>', UrlUpdateView.as_view(), name='url-detail'),
    path('u/<short_url>/', UrlRedirectView.as_view(), name='redirect-short-url'),
    path('urls/delete/<pk>/', UrlDeleteView.as_view(), name='url-delete'),
    path('login/', UserLoginView.as_view(redirect_authenticated_user = True), name='user-login'),
    path('logout/', LogoutView.as_view(), name='user-logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('change-password/', PasswordChangeView.as_view()),
    path('userlist/', SeeAdminsView.as_view(), name='users-list'),
]



tinyapp/models.py
from enum import auto
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# Definition of User model
class User(AbstractUser):
    def __str__(self):
        return self.first_name + " " + self.last_name

# Definition of URL model
class Url(models.Model):
    short_url = models.CharField(verbose_name='Short URL', max_length=6,unique=True)
    long_url = models.URLField(verbose_name='Long URL',max_length=5000)
    user = models.ForeignKey('User',on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now=True)
    slug_field = models.SlugField(max_length=5000)
    
    def __str__(self):
        return self.short_url

    def get_absolute_url(self):
       return reverse('url-detail', kwargs={'pk':self.pk,'slug': self.slug_field})

class Visitor(models.Model):
    visitor_id = models.CharField(max_length=20)
    short_url = models.CharField(max_length=6)
    time_visited = models.DateTimeField(auto_now=True)

templates/admin.html
{% extends "base.html" %}

{% block title %}My Tiny Users{% endblock %}

{% block content %}

  <br/>
  <main class="container">
      {% if users %}
        <h3>TinyApp Users</h3>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">First Name</th>   
                <th scope="col">Last Name</th>   
                <th scope="col">Email</th>
            </tr>
            </thead>
            <tbody>    
                {% for user in users %}
                    <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}     
            </tbody>
        </table>
      {%else%}
        <h1>You do not have permissions to view this page</h1>
      {% endif %}
  </main>

{% endblock %}

templates/base.html
<!--This is the base template that will be extended in all the other child templates--> 
<!DOCTYPE html>
<html lang="en">
  <head>
    {# Load the tag library #} 
    {% load bootstrap5 %} 
    {# Load CSS and JavaScript #}
    {% bootstrap_css %} {% bootstrap_javascript %}

    <title>{% block title %} {% endblock %}</title>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">TinyApp</a>
            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                    {% with request.resolver_match.url_name as url_name %}
                      <li class="nav-item">
                        <a class="nav-link {% if url_name == 'url-list' %}active{% endif %}" href="{% url 'url-list' %}">My URLs</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link {% if url_name == 'url-new' %}active{% endif %}" href="{% url 'url-new' %}">Create New URL</a>
                      </li>
                      {% if perms.tinyapp.view_user %}
                        <li class="nav-item">
                          <a class="nav-link {% if url_name == 'users-list' %}active{% endif %}" href="{% url 'users-list' %}">Users List</a>
                        </li>
                      {% endif %}
                    {% endwith %}
                  {% else %}
                    {% with request.resolver_match.url_name as url_name %}
                      <li class="nav-item">
                        <a class="nav-link {% if url_name == 'register-user' %}active{% endif %}" href="{% url 'register-user' %}">Create new account</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link {% if url_name == 'user-login' %}active{% endif %}" href="{% url 'user-login' %}">Login</a>
                      </li>
                    {% endwith %}
                  {% endif %}
              </ul>
            </div>
            {% if user.is_authenticated %}
              <div class="navbar-brand">Welcome {{username}}!</div>
              <form method="get" action="/logout/">{% csrf_token %}
                <div><button class="btn btn-danger" type="submit">Log out</button></div>
              </form>
            {% endif %}
        </div>
      </nav>
    </header>

    <div class="container">
        {% block content %} 
        {% endblock %}
    </div>
  </body>
</html>

templates/register.html
<!--Template for user registration form--> 
{% extends "base.html" %}

{% block title %}Register{% endblock %} 

{% load crispy_forms_tags %}

{% block content %}
</br>
<div class="container">
  <div class="card w-50 mx-auto">
    <h1 class="card-header">Sign up for TinyApp</h1>
    <div class="card-body">
      <form method="post">
        {% csrf_token %} {{ form | crispy }}
        <button type="submit" class="btn btn-success">Sign Up</button>       
      </form>
      <br/>
      <a href="{% url 'user-login' %}">Already registered? Log in now!</a>
    </div>
  </div>
</div>
{% endblock %}

templates/url_detail.html
<!--Template to display details of a long URL and its corresponding short URL--> 
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}URL Details{% endblock %}

{% block content %}

  <br/>
  {% if user.is_authenticated %}
    <div class="card">
      <div class="card-header">    
        <div class="row">
          <div class="col-sm-5"><h5>Total Visits: {{total_visits}}</h5></div>
          <div class="col-sm-5"><h4>Edit URL Details</h4></div>
          <div class="col-sm-2"><h5>Unique Visits: {{unique_visits}}</h5></div>
          </div>
      </div>  
      <div class="card-body">
        <div class="text-center">
          <h4 class="card-text">Short URL: <a href="{% url 'redirect-short-url' url.short_url %}">{{ url.short_url }}</a></h4>
        </div>
      </div>
      <div class="card-footer text-muted">
        <form method="post">
          {% csrf_token %} {{ form | crispy }} 
          <button type="submit" class="btn btn-success mt-2">Update</button>
        </form>
      </div>
    </div>
    <br/>
    <div class="text-center"><h2>Visitor data</h2></div>
        <table class="table table-bordered">
          <thead>
            <tr>
                <th scope="col" class="text-center">Visitor ID</th>
                <th scope="col" class="text-center">Time Visited</th> 
            </tr>
          </thead>
          {% for v in visitors %}
          <tr>
            <td class="text-center">{{ v.visitor_id }}</td>
            <td class="text-center">{{ v.time_visited }}</td>
          </tr>
          {% endfor %}
        </table>
  {%else%}
    <h1>You are not signed in! Please <a href="{% url 'user-login' %}">Login</a> or <a href="{% url 'register-user' %}">Register</a></h1>
  {% endif %}
{% endblock %}

templates/urls_index.html
<!--Template for displaying list of all URLs saved in the database--> 

{% extends "base.html" %}

{% block title %}My tiny URLs{% endblock %}

{% block content %}

  <br/>
  <main class="container">
      <table class="table">
          <thead>
          <tr>
              <th scope="col">Long URL</th>
              <th scope="col">Short URL</th>   
              <th scope="col">Edit</th>   
              <th scope="col">Delete</th>
          </tr>
          </thead>
          <tbody>    
            {% for url in urls %}
                <tr>
                  <td>{{ url.long_url }}</td>
                  <td><a href="{% url 'redirect-short-url' url.short_url %}">{{ url.short_url }}</a></td>
                  <td>
                    <form method="GET" action="{{url.get_absolute_url}}">{% csrf_token %}
                        <button class="btn btn-primary" type="submit">Edit</button>
                    </form>
                  </td>
                  <td>
                    <form method="POST" action="/urls/delete/{{url.id}}/">{% csrf_token %}
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                  </td>
                </tr>
            {% endfor %}     
          </tbody>
      </table>
  </main>

{% endblock %}

templates/urls_new.html
<!--Template for create short URL form--> 

{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Create Tiny URL{% endblock %} 
{% block content %}
  <br/>
  <div class="card">
    <div class="card-header">        
      <h1>Create Tiny URL</h1>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %} {{ form | crispy }}  
        <button type="submit" class="btn btn-primary mt-2">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}